### ISSUE TITLE
Support 3.10 and other architectures.

### ISSUE THREAD

**Issue by vicky5124** [rillrate/rillrate-py#1]
Currently, the library does not install on the newly released 3.10 python version, this is because wheels are only built for 3.6 to 3.9

`"3.10"` should be added to the list of python versions, in CI, and PyPi Releases:
```yml
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, "3.10"] # 3.10 w/o quotes will be read as 3.1
        os: [ubuntu-latest, macos-latest, windows-latest]
```

Additionally, this library cannot be installed when using a 32 bit system, or an ARM system, because only x86_64 builds are made; this makes the library not be able to be installed via PyPi on 32 bit Windows or Linux systems, modern systems like the M1 Macs, and other ARM systems like the Raspberri Pi, or Android systems with Termux or PyDroid.

https://github.com/Daggy1234/polaroid/blob/main/.github/workflows/publish.yml
Check out how other pyo3 libraries build for ARM, like for example `polaroid`.
